SUPERTONIC_ENGINE_ID = "supertonic"
KOKORO_ENGINE_ID = "kokoro"

DEFAULT_TTS_ENGINE = SUPERTONIC_ENGINE_ID
DEFAULT_SUPERTONIC_VOICE = "M1"
DEFAULT_KOKORO_VOICE = "af_heart"
DEFAULT_TTS_VOICE = DEFAULT_SUPERTONIC_VOICE
DEFAULT_TTS_SPEED = 1.0
